# -*- coding: utf-8 -*-
"""base_conocimiento_en_desarrollo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6L7pV9Y-Yk6mQ4H7eKnPyDxrBqosg-z

# EN ETAPA DE DESARROLLO: Base de Conocimiento Estructurada

## Taxonomía de Pilares de Ciencia Abierta

Para la definición de la taxonomÍa utilizada en el entrenamiento se revisaron los siguientes documentos, recomendaciones de CA de la UNESCO (2021) y  Taxonomia da Ciência Aberta: revisada e ampliada, además del material del su curso de OpenScience 101 desarrollado por por Nasa. En estos se identificaron distintas taxonomías como Pontika et al. (2015), Baumgartner (2019), Silveira et al. (2021), y una última ampliada. Finalmente, se decidió establecer una clasificación basada en las recomendaciones de la Unesco para la ciencia abierta y en los módulos definidos en el curso de OpenScience 101. La misma consiste en: acceso_abierto.datos abiertos, codigo_abierto, evaluacion_abierta y ciencia_ciudadana.

Fuente: Artículo: SciELO Brasil - Taxonomia da Ciência Aberta: revisada e ampliada Taxonomia da Ciência Aberta: revisada e ampliada https://share.google/C0r8ikdeLFwAGjR2u.
"""

PILARES_CA = {
    "acceso_abierto": {
        "subcategorias": ["publicaciones", "repositorios", "preprints"],
        "entidades": ["revistas", "editoriales", "licencias"]
    },
    "datos_abiertos": {
        "subcategorias": ["FAIR", "repositorios", "metadatos"],
        "entidades": ["formatos", "identificadores", "planes_gestion"]
    },
    "codigo_abierto": {
        "subcategorias": ["software", "notebooks", "reproducibilidad"],
        "entidades": ["licencias", "plataformas", "versionado", "lenguaje"]
    },
    "evaluacion_abierta": {
        "subcategorias": ["peer_review", "metricas", "transparencia"],
        "entidades": ["altmetrics", "sistemas_evaluacion"]
    },
    "ciencia_ciudadana": {
        "subcategorias": ["participacion", "metodologias", "plataformas"],
        "entidades": ["proyectos", "herramientas", "comunidades"]
    }
}

"""## Estructura de Pares Pregunta-Respuesta"""

class QAPair:
    def __init__(self):
        self.pregunta = ""
        self.respuesta = ""
        self.pilar = ""
        self.nivel_complejidad = ""  # básico, intermedio, avanzado
        self.audiencia = ""  # maestría, doctorado, investigador
        self.contexto_regional = ""  # América Latina específico
        self.fuentes = []
        self.entidades_relacionadas = []

"""## Ejemplo de Par pregunta-respuesta.

  **"pregunta":** "¿Cuáles son las principales barreras identificadas para la implementación del acceso abierto a las publicaciones científicas en América Latina según el estudio CILAC 2021?",
    
  **"respuesta":** "Según el documento CILAC 2021, las principales barreras incluyen: 1) La estructura oligopólica del mercado editorial científico que genera barreras económicas y técnicas; 2) Los sistemas de evaluación académica basados en el factor de impacto que privilegian publicaciones en revistas comerciales de alto costo; 3) La falta de transparencia en los costos de suscripciones y APCs que impide una negociación efectiva; 4) La resistencia cultural de los investigadores acostumbrados al modelo tradicional; y 5) La fragmentación de políticas nacionales sin suficiente coordinación regional. El estudio destaca que América Latina gasta aproximadamente 200 millones de dólares anuales en suscripciones, recursos que podrían redirigirse hacia modelos de publicación abierta más sostenibles.",
      
  **"pilar":** "acceso_abierto",

  **"nivel_complejidad":** "avanzado",

  **"audiencia": "**investigador",

  **"contexto_regional":** "Específico de América Latina - análisis de barreras estructurales y económicas en la región",

 **"fuentes":** ["CILAC 2021 - Ciencia Abierta en América Latina", "La Referencia - Primera Encuesta Regional sobre Negociación y Contratación"],
  "entidades_relacionadas": ["revistas comerciales", "factor de impacto","APCs", "SciELO", "La Referencia"]
"""